@startgantt
project starts 2025-06-04

[Sprint 1] starts 2025-06-04 and lasts 5 days
[Sprint 2] starts 2025-06-11 and lasts 5 days
[Sprint 3] starts 2025-06-18 and lasts 5 days

-- Подготовка --
[Изучение UI API GitHub/GitFlic] starts 2025-06-04 and ends 2025-06-04
[Выбор UI библиотек] starts 2025-06-04 and ends 2025-06-04

-- Sprint 1 (MVP) --
[Настройка UI окружения] starts 2025-06-05 and lasts 2 days
[Базовый интерфейс] starts 2025-06-05 and lasts 2 days
[Интеграция OAuth UI] starts 2025-06-07 and lasts 1 days
[UI тестирование и документация MVP] starts 2025-06-08 and lasts 1 days

-- Sprint 2 --
[UI/UX улучшения] starts 2025-06-11 and lasts 2 days
[Интерфейс GitFlic] starts 2025-06-13 and lasts 2 days
[UI тестирование и документация интеграции] starts 2025-06-15 and lasts 1 days

-- Sprint 3 --
[Оптимизация UX] starts 2025-06-18 and lasts 2 days
[Финальное UI тестирование] starts 2025-06-20 and lasts 1 days
[Финальная документация UI] starts 2025-06-21 and lasts 1 days
[Подготовка UI к релизу] starts 2025-06-22 and lasts 1 days

@endgantt 